.TH MILKJAR 5
.SH NAME
milkjar \- pack Java \s-1JAR\s0 files as \s-1UNIX\s0 executables
.SH SYNOPSIS
.B milkjar [-i] <input.jar> [-o] <output>
.SH DESCRIPTION
.B milkjar 
is a tool for packing java \s-1JAR\s0 files into \s-1UNIX\s0 executables. It is part
of the milksteak package manager where it is used for installing Java programs but it
can also be used on its own for the same purpose.
